/*
 * Kinde Management API
 *
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddOrganizationUsersRequest {
    /// Users to be added to the organization.
    #[serde(rename = "users", skip_serializing_if = "Option::is_none")]
    pub users: Option<Vec<crate::models::AddOrganizationUsersRequestUsersInner>>,
}

impl AddOrganizationUsersRequest {
    pub fn new() -> AddOrganizationUsersRequest {
        AddOrganizationUsersRequest {
            users: None,
        }
    }
}


