/*
 * Kinde Management API
 *
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddOrganizationUsersResponse {
    /// Response code.
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    /// Response message.
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "users_added", skip_serializing_if = "Option::is_none")]
    pub users_added: Option<Vec<String>>,
}

impl AddOrganizationUsersResponse {
    pub fn new() -> AddOrganizationUsersResponse {
        AddOrganizationUsersResponse {
            code: None,
            message: None,
            users_added: None,
        }
    }
}


