/*
 * Kinde Management API
 *
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddApisRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "audience")]
    pub audience: String,
}

impl AddApisRequest {
    pub fn new(name: String, audience: String) -> AddApisRequest {
        AddApisRequest {
            name,
            audience,
        }
    }
}


