/*
 * Kinde Management API
 *
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConnectedAppsAuthUrl {
    /// A URL that is used to authenticate an end-user against a connected app.
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// A unique identifier for the login session.
    #[serde(rename = "session_id", skip_serializing_if = "Option::is_none")]
    pub session_id: Option<String>,
}

impl ConnectedAppsAuthUrl {
    pub fn new() -> ConnectedAppsAuthUrl {
        ConnectedAppsAuthUrl {
            url: None,
            session_id: None,
        }
    }
}


