/*
 * Kinde Management API
 *
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConnectedAppsAccessToken {
    /// The access token to access a third-party provider.
    #[serde(rename = "access_token", skip_serializing_if = "Option::is_none")]
    pub access_token: Option<String>,
    /// The date and time that the access token expires.
    #[serde(rename = "access_token_expiry", skip_serializing_if = "Option::is_none")]
    pub access_token_expiry: Option<String>,
}

impl ConnectedAppsAccessToken {
    pub fn new() -> ConnectedAppsAccessToken {
        ConnectedAppsAccessToken {
            access_token: None,
            access_token_expiry: None,
        }
    }
}


