/*
 * Kinde Management API
 *
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateOrganizationRequest {
    /// The organization's name.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The organization's feature flag settings.
    #[serde(rename = "feature_flags", skip_serializing_if = "Option::is_none")]
    pub feature_flags: Option<FeatureFlags>,
    /// The organization's ID.
    #[serde(rename = "external_id", skip_serializing_if = "Option::is_none")]
    pub external_id: Option<String>,
    /// The organization's brand settings - background color.
    #[serde(rename = "background_color", skip_serializing_if = "Option::is_none")]
    pub background_color: Option<String>,
    /// The organization's brand settings - button color.
    #[serde(rename = "button_color", skip_serializing_if = "Option::is_none")]
    pub button_color: Option<String>,
    /// The organization's brand settings - button text color.
    #[serde(rename = "button_text_color", skip_serializing_if = "Option::is_none")]
    pub button_text_color: Option<String>,
    /// The organization's brand settings - link color.
    #[serde(rename = "link_color", skip_serializing_if = "Option::is_none")]
    pub link_color: Option<String>,
    /// The organization's handle.
    #[serde(rename = "handle", skip_serializing_if = "Option::is_none")]
    pub handle: Option<String>,
}

impl CreateOrganizationRequest {
    pub fn new() -> CreateOrganizationRequest {
        CreateOrganizationRequest {
            name: None,
            feature_flags: None,
            external_id: None,
            background_color: None,
            button_color: None,
            button_text_color: None,
            link_color: None,
            handle: None,
        }
    }
}

/// The organization's feature flag settings.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FeatureFlags {
    #[serde(rename = "str")]
    Str,
    #[serde(rename = "int")]
    Int,
    #[serde(rename = "bool")]
    Bool,
}

impl Default for FeatureFlags {
    fn default() -> FeatureFlags {
        Self::Str
    }
}

