/*
 * Kinde Management API
 *
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateSubscriberSuccessResponse {
    #[serde(rename = "subscriber", skip_serializing_if = "Option::is_none")]
    pub subscriber: Option<Box<crate::models::CreateSubscriberSuccessResponseSubscriber>>,
}

impl CreateSubscriberSuccessResponse {
    pub fn new() -> CreateSubscriberSuccessResponse {
        CreateSubscriberSuccessResponse {
            subscriber: None,
        }
    }
}


