/*
 * Kinde Management API
 *
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateOrganizationResponseOrganization {
    /// The organization's code.
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
}

impl CreateOrganizationResponseOrganization {
    pub fn new() -> CreateOrganizationResponseOrganization {
        CreateOrganizationResponseOrganization {
            code: None,
        }
    }
}


