/*
 * Kinde Management API
 *
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateOrganizationUserPermissionRequest {
    /// The permission id.
    #[serde(rename = "permission_id", skip_serializing_if = "Option::is_none")]
    pub permission_id: Option<String>,
}

impl CreateOrganizationUserPermissionRequest {
    pub fn new() -> CreateOrganizationUserPermissionRequest {
        CreateOrganizationUserPermissionRequest {
            permission_id: None,
        }
    }
}


