/*
 * Kinde Management API
 *
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateOrganizationUserRoleRequest {
    /// The role id.
    #[serde(rename = "role_id", skip_serializing_if = "Option::is_none")]
    pub role_id: Option<String>,
}

impl CreateOrganizationUserRoleRequest {
    pub fn new() -> CreateOrganizationUserRoleRequest {
        CreateOrganizationUserRoleRequest {
            role_id: None,
        }
    }
}


