/*
 * Kinde Management API
 *
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 * Generated by: https://openapi-generator.tech
 */

/// CreateUserRequestProfile : Basic information required to create a user.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateUserRequestProfile {
    /// User's first name.
    #[serde(rename = "given_name", skip_serializing_if = "Option::is_none")]
    pub given_name: Option<String>,
    /// User's last name.
    #[serde(rename = "family_name", skip_serializing_if = "Option::is_none")]
    pub family_name: Option<String>,
}

impl CreateUserRequestProfile {
    /// Basic information required to create a user.
    pub fn new() -> CreateUserRequestProfile {
        CreateUserRequestProfile {
            given_name: None,
            family_name: None,
        }
    }
}


