/*
 * Kinde Management API
 *
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetRedirectCallbackUrlsResponse {
    /// An application's redirect callback URLs.
    #[serde(rename = "redirect_urls", skip_serializing_if = "Option::is_none")]
    pub redirect_urls: Option<Vec<crate::models::RedirectCallbackUrls>>,
}

impl GetRedirectCallbackUrlsResponse {
    pub fn new() -> GetRedirectCallbackUrlsResponse {
        GetRedirectCallbackUrlsResponse {
            redirect_urls: None,
        }
    }
}


