/*
 * Kinde Management API
 *
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSubscriberResponse {
    /// Response code.
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    /// Response message.
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "subscribers", skip_serializing_if = "Option::is_none")]
    pub subscribers: Option<Vec<crate::models::Subscriber>>,
}

impl GetSubscriberResponse {
    pub fn new() -> GetSubscriberResponse {
        GetSubscriberResponse {
            code: None,
            message: None,
            subscribers: None,
        }
    }
}


