/*
 * Kinde Management API
 *
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetEnvironmentFeatureFlagsResponse {
    /// Response code.
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    /// Response message.
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    /// The environment's feature flag settings.
    #[serde(rename = "feature_flags", skip_serializing_if = "Option::is_none")]
    pub feature_flags: Option<::std::collections::HashMap<String, crate::models::GetOrganizationFeatureFlagsResponseFeatureFlagsValue>>,
    /// Pagination token.
    #[serde(rename = "next_token", skip_serializing_if = "Option::is_none")]
    pub next_token: Option<String>,
}

impl GetEnvironmentFeatureFlagsResponse {
    pub fn new() -> GetEnvironmentFeatureFlagsResponse {
        GetEnvironmentFeatureFlagsResponse {
            code: None,
            message: None,
            feature_flags: None,
            next_token: None,
        }
    }
}


