/*
 * Kinde Management API
 *
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetOrganizationUsersResponse {
    /// Response code.
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    /// Response message.
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "organization_users", skip_serializing_if = "Option::is_none")]
    pub organization_users: Option<Vec<crate::models::OrganizationUser>>,
    /// Pagination token.
    #[serde(rename = "next_token", skip_serializing_if = "Option::is_none")]
    pub next_token: Option<String>,
}

impl GetOrganizationUsersResponse {
    pub fn new() -> GetOrganizationUsersResponse {
        GetOrganizationUsersResponse {
            code: None,
            message: None,
            organization_users: None,
            next_token: None,
        }
    }
}


