/*
 * Kinde Management API
 *
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrganizationUserRolePermissionsPermissions {
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
}

impl OrganizationUserRolePermissionsPermissions {
    pub fn new() -> OrganizationUserRolePermissionsPermissions {
        OrganizationUserRolePermissionsPermissions {
            key: None,
        }
    }
}


