/*
 * Kinde Management API
 *
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RedirectCallbackUrls {
    /// An application's redirect URLs.
    #[serde(rename = "redirect_urls", skip_serializing_if = "Option::is_none")]
    pub redirect_urls: Option<Vec<String>>,
}

impl RedirectCallbackUrls {
    pub fn new() -> RedirectCallbackUrls {
        RedirectCallbackUrls {
            redirect_urls: None,
        }
    }
}


