/*
 * Kinde Management API
 *
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReplaceLogoutRedirectUrlsRequest {
    /// Array of logout urls.
    #[serde(rename = "urls", skip_serializing_if = "Option::is_none")]
    pub urls: Option<Vec<String>>,
}

impl ReplaceLogoutRedirectUrlsRequest {
    pub fn new() -> ReplaceLogoutRedirectUrlsRequest {
        ReplaceLogoutRedirectUrlsRequest {
            urls: None,
        }
    }
}


