/*
 * Kinde Management API
 *
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateApplicationRequest {
    /// The application's name.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The application's language key.
    #[serde(rename = "language_key", skip_serializing_if = "Option::is_none")]
    pub language_key: Option<String>,
    /// The application's logout uris.
    #[serde(rename = "logout_uris", skip_serializing_if = "Option::is_none")]
    pub logout_uris: Option<Vec<String>>,
    /// The application's redirect uris.
    #[serde(rename = "redirect_uris", skip_serializing_if = "Option::is_none")]
    pub redirect_uris: Option<Vec<String>>,
}

impl UpdateApplicationRequest {
    pub fn new() -> UpdateApplicationRequest {
        UpdateApplicationRequest {
            name: None,
            language_key: None,
            logout_uris: None,
            redirect_uris: None,
        }
    }
}


