/*
 * Kinde Management API
 *
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateUserRequest {
    /// User's first name.
    #[serde(rename = "given_name", skip_serializing_if = "Option::is_none")]
    pub given_name: Option<String>,
    /// User's last name.
    #[serde(rename = "family_name", skip_serializing_if = "Option::is_none")]
    pub family_name: Option<String>,
    /// Whether the user is currently suspended or not.
    #[serde(rename = "is_suspended", skip_serializing_if = "Option::is_none")]
    pub is_suspended: Option<bool>,
    /// Prompt the user to change their password on next sign in.
    #[serde(rename = "is_password_reset_requested", skip_serializing_if = "Option::is_none")]
    pub is_password_reset_requested: Option<bool>,
}

impl UpdateUserRequest {
    pub fn new() -> UpdateUserRequest {
        UpdateUserRequest {
            given_name: None,
            family_name: None,
            is_suspended: None,
            is_password_reset_requested: None,
        }
    }
}


