/*
 * Kinde Management API
 *
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateRolePermissionsRequestPermissionsInner {
    /// The permission id.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Optional operation, set to 'delete' to remove the permission from the role.
    #[serde(rename = "operation", skip_serializing_if = "Option::is_none")]
    pub operation: Option<String>,
}

impl UpdateRolePermissionsRequestPermissionsInner {
    pub fn new() -> UpdateRolePermissionsRequestPermissionsInner {
        UpdateRolePermissionsRequestPermissionsInner {
            id: None,
            operation: None,
        }
    }
}


