/*
 * Kinde Management API
 *
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateApiApplicationsRequest {
    #[serde(rename = "applications")]
    pub applications: Vec<crate::models::UpdateApiApplicationsRequestApplicationsInner>,
}

impl UpdateApiApplicationsRequest {
    pub fn new(applications: Vec<crate::models::UpdateApiApplicationsRequestApplicationsInner>) -> UpdateApiApplicationsRequest {
        UpdateApiApplicationsRequest {
            applications,
        }
    }
}


