/*
 * Kinde Management API
 *
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateRolePermissionsResponse {
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "permissions_added", skip_serializing_if = "Option::is_none")]
    pub permissions_added: Option<Vec<String>>,
    #[serde(rename = "permissions_removed", skip_serializing_if = "Option::is_none")]
    pub permissions_removed: Option<Vec<String>>,
}

impl UpdateRolePermissionsResponse {
    pub fn new() -> UpdateRolePermissionsResponse {
        UpdateRolePermissionsResponse {
            code: None,
            message: None,
            permissions_added: None,
            permissions_removed: None,
        }
    }
}


