/*
 * Kinde Management API
 *
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateRolePermissionsRequest {
    /// Permissions to add or remove from the role.
    #[serde(rename = "permissions", skip_serializing_if = "Option::is_none")]
    pub permissions: Option<Vec<crate::models::UpdateRolePermissionsRequestPermissionsInner>>,
}

impl UpdateRolePermissionsRequest {
    pub fn new() -> UpdateRolePermissionsRequest {
        UpdateRolePermissionsRequest {
            permissions: None,
        }
    }
}


