/*
 * Kinde Management API
 *
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserProfileV2 {
    /// Unique id of the user in Kinde (deprecated).
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Unique id of the user in Kinde.
    #[serde(rename = "sub", skip_serializing_if = "Option::is_none")]
    pub sub: Option<String>,
    /// Value of the user's id in a third-party system when the user is imported into Kinde.
    #[serde(rename = "provided_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub provided_id: Option<Option<String>>,
    /// Users's first and last name separated by a space.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// User's first name.
    #[serde(rename = "given_name", skip_serializing_if = "Option::is_none")]
    pub given_name: Option<String>,
    /// User's last name.
    #[serde(rename = "family_name", skip_serializing_if = "Option::is_none")]
    pub family_name: Option<String>,
    /// Date the user was last updated at (In Unix time).
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<i32>,
    /// User's email address if available.
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// URL that point's to the user's picture or avatar
    #[serde(rename = "picture", skip_serializing_if = "Option::is_none")]
    pub picture: Option<String>,
}

impl UserProfileV2 {
    pub fn new() -> UserProfileV2 {
        UserProfileV2 {
            id: None,
            sub: None,
            provided_id: None,
            name: None,
            given_name: None,
            family_name: None,
            updated_at: None,
            email: None,
            picture: None,
        }
    }
}


